

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 40  keV
/Generator/SingleParticle/max_energy 2.6 MeV
#/Generator/IonGenerator/atomic_number 54 # this is for Xe 137 decays
#/Generator/IonGenerator/mass_number 137


##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 30  keV
/Actions/DefaultEventAction/max_energy 2.6 MeV

## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

#GEOMETRY
/Geometry/ATPC/gas_pressure 1 bar
/Geometry/ATPC/cube_size  10 m
/Geometry/ATPC/chamber_thickn 4 cm
/Geometry/ATPC/max_step_size 1 mm

/Geometry/ATPC/detgeom cylinder
/Generator/SingleParticle/region CuCylinderActive

# PERSISTENCY
#/nexus/persistency/eventType background
/nexus/random_seed            9800
/nexus/persistency/start_id   0
/nexus/persistency/output_file ATPC_single
