

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/region CENTER
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 30. keV
/Generator/SingleParticle/max_energy 2.5 MeV


##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 30 keV
/Actions/DefaultEventAction/max_energy 2.50 MeV

## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

#GEOMETRY
/Geometry/ATPC/gas_pressure 10. bar
/Geometry/ATPC/cube_size  6 m
/Geometry/ATPC/chamber_thickn 5 cm

# PERSISTENCY
#/nexus/persistency/eventType background
/nexus/random_seed            9800
/nexus/persistency/start_id   0
/nexus/persistency/output_file ATPC_single
