## ----------------------------------------------------------------------------
## nexus | NextTonScale.config.mac
##
## Configuration macro to simulate individual particles
## in the NEXT tonne-scale detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0
/process/had/verbose 0

### GEOMETRY
/Geometry/NextTonScale/active_diam   260. cm
/Geometry/NextTonScale/active_length 260. cm
/Geometry/NextTonScale/fcage_thickn   0.5 cm
/Geometry/NextTonScale/ics_thickn     12. cm
/Geometry/NextTonScale/vessel_thickn   2. cm

/Geometry/NextTonScale/gas enrichedXe
/Geometry/NextTonScale/gas_pressure     15. bar
/Geometry/NextTonScale/gas_temperature 300. kelvin

/Geometry/NextTonScale/tank_visibility    true
/Geometry/NextTonScale/vessel_visibility  true
/Geometry/NextTonScale/ics_visibility     true
/Geometry/NextTonScale/fcage_visibility   true
/Geometry/NextTonScale/cathode_visibility true
/Geometry/NextTonScale/anode_visibility   true
/Geometry/NextTonScale/readout_visibility true

### GENERATOR
# # Single Particle
# /Generator/SingleParticle/region AD_HOC
# /Geometry/NextTonScale/specific_vertex 0. 0. 0. mm
# /Generator/SingleParticle/particle geantino
# /Generator/SingleParticle/min_energy 1. GeV
# /Generator/SingleParticle/max_energy 1. GeV
# /Generator/SingleParticle/momentum 0 0 1

# Ion Generator for background decays... (Bi214: Z=83, A=214), (Tl208: Z=81, A=208)
# /Generator/IonGenerator/region INNER_SHIELDING
# /Generator/IonGenerator/atomic_number 83
# /Generator/IonGenerator/mass_number 214

# Decay0 interface for BB decays ... (BB0nu: DecayMode 1), (BB2nu: DecayMode 4)
/Generator/Decay0Interface/region ACTIVE
/Generator/Decay0Interface/inputFile none
/Generator/Decay0Interface/Xe136DecayMode 1
/Generator/Decay0Interface/EnergyThreshold 0. keV
/Generator/Decay0Interface/Ba136FinalState 0

### ACTIONS
/Actions/DefaultEventAction/min_energy 2.3 MeV
/Actions/DefaultEventAction/max_energy 2.6 MeV

### PHYSICS (for fast simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

# PERSISTENCY
#/nexus/persistency/eventType background
/nexus/random_seed            9800
/nexus/persistency/start_id   9800
/nexus/persistency/output_file NextTonScale_0nubb
